### ISSUE TITLE
Invalid definition for _likeCount error

### ISSUE THREAD

**Issue by rpeterson** [copleykj/socialize-likeable#1]
```
Error: Invalid definition for _likeCount field.
W20150701-10:35:39.411(-4)? (STDERR)     at packages/aldeed:simple-schema/simple-schema.js:465:1
W20150701-10:35:39.411(-4)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150701-10:35:39.411(-4)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed:simple-schema/simple-schema.js:462:1)
W20150701-10:35:39.411(-4)? (STDERR)     at packages/socialize:likeable/common/likeable-model.js:80:1
W20150701-10:35:39.411(-4)? (STDERR)     at .meteor/local/build/programs/server/packages/socialize_likeable.js:114:4
W20150701-10:35:39.411(-4)? (STDERR)     at .meteor/local/build/programs/server/packages/socialize_likeable.js:227:3
W20150701-10:35:39.411(-4)? (STDERR)     at .meteor/local/build/programs/server/boot.js:222:10
W20150701-10:35:39.411(-4)? (STDERR)     at Array.forEach (native)
W20150701-10:35:39.411(-4)? (STDERR)     at Function._.each._.forEach (.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150701-10:35:39.411(-4)? (STDERR)     at .meteor/local/build/programs/server/boot.js:117:5
```

**Comment by copleykj** [comment]
I'm not able to reproduce this, could you possibly link me to a repo that has this issue or create a reproduction?

**Comment by rpeterson** [comment]
I will see if I can't dig into it further to find the actual cause.

**Comment by rpeterson** [comment]
Was an implementation issue.
