### ISSUE TITLE
A typo in README

### ISSUE THREAD

**Issue by limingth** [copleykj/socialize-likeable#3]
`var Post = likeableModel.extend()`

likeableModel should be captilized like

`var Post = LikeableModel.extend()`

and I got this error message when I added the codes, Anyone can help?

```
var Post = LikeableModel.extend();

//BaseModel requires a prototype._collection so we do that here
Post.prototype._collection = Meteor.Collection("posts", {
    transform: function(document){
        return new Post(document);
    }
});

//expose the collection on the Meteor global
Meteor.posts = Post.prototype._collection;
```

```
=> Modified -- restarting.
W20151105-12:07:34.578(8)? (STDERR)           
W20151105-12:07:34.578(8)? (STDERR) /Users/limingth/.meteor/packages/meteor-tool/.1.1.10.1ttp3qs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151105-12:07:34.578(8)? (STDERR)                         throw(ex);
W20151105-12:07:34.578(8)? (STDERR)                               ^
W20151105-12:07:34.656(8)? (STDERR) Error: use "new" to construct a Mongo.Collection
W20151105-12:07:34.656(8)? (STDERR)     at Object.Mongo.Collection (packages/mongo/collection.js:29:1)
W20151105-12:07:34.656(8)? (STDERR)     at Object.ns.Collection (packages/matb33_collection-hooks/collection-hooks.js:244:1)
W20151105-12:07:34.656(8)? (STDERR)     at lib/collections/likeable.js:6:1
W20151105-12:07:34.656(8)? (STDERR)     at lib/collections/likeable.js:14:1
W20151105-12:07:34.657(8)? (STDERR)     at /Users/limingth/Github/Maodou/meteor-skeleton/.meteor/local/build/programs/server/boot.js:242:10
W20151105-12:07:34.657(8)? (STDERR)     at Array.forEach (native)
W20151105-12:07:34.657(8)? (STDERR)     at Function._.each._.forEach (/Users/limingth/.meteor/packages/meteor-tool/.1.1.10.1ttp3qs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151105-12:07:34.657(8)? (STDERR)     at /Users/limingth/Github/Maodou/meteor-skeleton/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by limingth** [comment]
I fixed this bug, the code should look like this:

```
var Post = LikeableModel.extend();

Posts._transform = function (document) {
   return new Post(document);
};

Post.prototype._collection = Posts;

// Meteor.posts = Post.prototype._collection;
```

```
//var post = Meteor.posts.findOne();
var post = Posts.findOne();

post.like();
```
